name: Meu Fluxo de Trabalho

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar o ambiente .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '5.x'

      - name: Restaurar dependências
        run: dotnet restore